version: '3.7'

services:
  app:
      image: 'pali-dic'
      build:
        context: .
      container_name: pali-dic-0
      restart: always
      depends_on:
        - db
      environment:
        - DB_URL=jdbc:postgresql://db:5432/pali-dic
        - DB_USERNAME=postgres
        - DB_PASSWORD=special-password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      env_file:
        - production.env

  db:
    image: 'postgres:13-alpine'
    container_name: db
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_DB=pali-dic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=special-password
    volumes:
      - ~/data/pali/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql